TP1 - Numpy - Josué BAQUERO

On importe la bibliothèque numpy:

In [1]:
import numpy as np

Fonction qui réalise une seule marche aléatoire 1D en fonction de p et N (sans boucle):

In [2]:
def single_random_walk(p, N):
    """
    Réalise une seule marche aléatoire 1D
    
    Paramètres:
    p (float): probabilité de faire un pas +1 (0 <= p <= 1)
    N (int): nombre de pas
    
    Returns:
    int: position finale après N pas
    """
    # Génère N nombres aléatoires entre 0 et 1
    random_numbers = np.random.random(N)
    
    # Convertit en pas +1 ou -1 selon la probabilité p
    steps = np.where(random_numbers < p, 1, -1)
    
    # Retourne la somme des pas (position finale)
    return np.sum(steps)

Fonction qui réalise M marches aléatoires et calcule la moyenne et l'écart-type des positions finales:

In [3]:
def monte_carlo_walks(p, N, M):
    """
    Réalise M marches aléatoires et calcule les statistiques
    
    Paramètres:
    p (float): probabilité de faire un pas +1 (0 <= p <= 1)
    N (int): nombre de pas par marche
    M (int): nombre de marches à réaliser
    
    Returns:
    tuple: (moyenne des positions finales, écart-type des positions finales)
    """
    # Réalise M marches aléatoires
    final_positions = np.array([single_random_walk(p, N) for _ in range(M)])
    
    # Calcule et retourne moyenne et écart-type
    return np.mean(final_positions), np.std(final_positions)

Paramètres de test:

In [4]:
p = 0.6  # Probabilité de faire un pas +1
N = 1000  # Nombre de pas par marche
M_values = [10, 100, 1000, 10000]  # Différentes valeurs de M à tester

On crée un tableau pour stocker les résultats:

In [5]:
results = np.zeros((2, len(M_values)))
print(results)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


On réalise les diffférentes marches aléatoires pour les différentes valeurs de M puis on les stocke:

In [6]:
for i,M in enumerate(M_values):
    mean, std = monte_carlo_walks(p,N,M)
    results[0, i] = mean  # Stocke la moyenne
    results[1, i] = std   # Stocke l'écart-type
print(results)

[[193.4        198.42       198.878      200.4576    ]
 [ 21.46718426  30.94549402  30.99498534  31.02481913]]


On calcule ensuite les valeurs théoriques de la moyenne du déplacement ( = N*(2p-1)) et la variance ( = N * 4p*(1-p)):

In [7]:
theoretical_mean = N * (2*p - 1) #moyenne
theoretical_std = np.sqrt(N * 4*p*(1-p)) #écart-type

Maintenant on peut afficher l'ensemble des résultats de l'exercice:

In [8]:
print(f"Paramètres: p={p}, N={N}")
print("\nRésultats expérimentaux:") #\n pour saut à la ligne
print("M\tMoyenne\t\tÉcart-type") #\t pour une tabulation
print("-" * 40) #on trace un trait
for i, M in enumerate(M_values):
    print(f"{M}\t{results[0,i]:.2f}\t\t{results[1,i]:.2f}") #2 décimales de précision

print("\nValeurs théoriques:")
print(f"Moyenne théorique: {theoretical_mean:.2f}")
print(f"Écart-type théorique: {theoretical_std:.2f}")

Paramètres: p=0.6, N=1000

Résultats expérimentaux:
M	Moyenne		Écart-type
----------------------------------------
10	193.40		21.47
100	198.42		30.95
1000	198.88		30.99
10000	200.46		31.02

Valeurs théoriques:
Moyenne théorique: 200.00
Écart-type théorique: 30.98


Et on peut aussi sauvegarder nos résultats dans un fichier .npy

In [9]:
np.save('random_walk_results.npy', results)

Le fichier sera alors stocké dans "téléchargements" de l'ordi de l'école

On peut également ouvrir le fichier d'un autre élève (aussi situé dans téléchargements):

In [10]:
#other_results = np.load('fichier_du_voisin.npy')
#print(other_results)